/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.person;

/**
 *
 * @author Revanth
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    person Person;
    ImageIcon ii;
    Image im;
    public CreatePanel(person Person) {
        initComponents();
        this.Person = Person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProfile = new javax.swing.JLabel();
        labellName = new javax.swing.JLabel();
        labelGeographicalData = new javax.swing.JLabel();
        labelDateOfBirth = new javax.swing.JLabel();
        labelTelephoneNumber = new javax.swing.JLabel();
        labelFAXNumber = new javax.swing.JLabel();
        labelEmailAddress = new javax.swing.JLabel();
        labelSocialSecurityNumbers = new javax.swing.JLabel();
        labelMedicalRecordNumbers = new javax.swing.JLabel();
        labelBenificarNumbers = new javax.swing.JLabel();
        labelBankaccountNumber = new javax.swing.JLabel();
        labelCertificate = new javax.swing.JLabel();
        labelVehicleIdentifier = new javax.swing.JLabel();
        labelDeviceIdentifier = new javax.swing.JLabel();
        labelLinkedin = new javax.swing.JLabel();
        labelIPAddress = new javax.swing.JLabel();
        labelBiometric = new javax.swing.JLabel();
        labelPhoto = new javax.swing.JLabel();
        labelUniqueId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeographicaldata = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        txtFaxNumber = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtSocialSecurityNumber = new javax.swing.JTextField();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtHealthPlanNumber = new javax.swing.JTextField();
        txtBankAccountNumber = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        txtVehicleIdentifier = new javax.swing.JTextField();
        txtDeviceIdentifier = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtIPAddress = new javax.swing.JTextField();
        txtBiometricIdentifiers = new javax.swing.JTextField();
        txtPhoto = new javax.swing.JTextField();
        txtUniqueIdentifier = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();

        labelProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelProfile.setText("                                             Create Profile");

        labellName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labellName.setText("Name");

        labelGeographicalData.setText("Geographic data");

        labelDateOfBirth.setText("Date of birth");

        labelTelephoneNumber.setText("Telephone numbers");

        labelFAXNumber.setText("FAX number");

        labelEmailAddress.setText("Email addresses");

        labelSocialSecurityNumbers.setText("Social Security number");

        labelMedicalRecordNumbers.setText("Medical record number");

        labelBenificarNumbers.setText("Health plan  number");

        labelBankaccountNumber.setText("Bank account numbers");

        labelCertificate.setText("License number");

        labelVehicleIdentifier.setText("Vehicle identifiers ");

        labelDeviceIdentifier.setText("Device Identifiers ");

        labelLinkedin.setText("LinkedIn");

        labelIPAddress.setText("IP Address");

        labelBiometric.setText("Biometric identifiers");

        labelPhoto.setText("Full face photos ");

        labelUniqueId.setText(" unique identifying number");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtGeographicaldata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeographicaldataActionPerformed(evt);
            }
        });

        txtEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddressActionPerformed(evt);
            }
        });

        txtVehicleIdentifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdentifierActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblImage.setText("Image");

        btnImage.setText("Browse");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelBankaccountNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelFAXNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTelephoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelGeographicalData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labellName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelMedicalRecordNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelSocialSecurityNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addComponent(labelBenificarNumbers))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGeographicaldata)
                            .addComponent(txtDateOfBirth)
                            .addComponent(txtTelephoneNumber)
                            .addComponent(txtFaxNumber)
                            .addComponent(txtEmailAddress)
                            .addComponent(txtSocialSecurityNumber)
                            .addComponent(txtMedicalRecordNumber)
                            .addComponent(txtHealthPlanNumber)
                            .addComponent(txtBankAccountNumber)
                            .addComponent(txtLicenseNumber)
                            .addComponent(txtName))
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelLinkedin)
                                            .addGap(93, 93, 93))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(9, 9, 9))
                                        .addComponent(labelIPAddress)
                                        .addComponent(labelBiometric)
                                        .addComponent(labelVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelUniqueId)
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVehicleIdentifier)
                            .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkedin)
                            .addComponent(txtIPAddress)
                            .addComponent(txtBiometricIdentifiers)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPhoto)
                                .addGap(18, 18, 18)
                                .addComponent(btnImage))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUniqueIdentifier)
                                .addGap(18, 18, 18)
                                .addComponent(btnSubmit)))
                        .addGap(39, 39, 39)))
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBankAccountNumber, txtBiometricIdentifiers, txtDateOfBirth, txtDeviceIdentifier, txtEmailAddress, txtFaxNumber, txtGeographicaldata, txtHealthPlanNumber, txtIPAddress, txtLicenseNumber, txtLinkedin, txtMedicalRecordNumber, txtName, txtPhoto, txtSocialSecurityNumber, txtTelephoneNumber, txtUniqueIdentifier, txtVehicleIdentifier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labellName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGeographicalData)
                    .addComponent(txtGeographicaldata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDateOfBirth)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFAXNumber)
                    .addComponent(txtFaxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSocialSecurityNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSocialSecurityNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMedicalRecordNumbers)
                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBenificarNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHealthPlanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBankaccountNumber)
                    .addComponent(txtBankAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVehicleIdentifier)
                            .addComponent(labelVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLinkedin)
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIPAddress)
                            .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBiometric)
                            .addComponent(txtBiometricIdentifiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImage))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelUniqueId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUniqueIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtGeographicaldataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeographicaldataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeographicaldataActionPerformed

    private void txtVehicleIdentifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdentifierActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        //TODO add your handling code here:
        Person.setName(txtName.getText());
        Person.setGeographicdata(txtGeographicaldata.getText());
        Person.setDate_of_birth(txtDateOfBirth.getText());
        Person.setTelephone_number(Long.valueOf(txtTelephoneNumber.getText()));
        Person.setFax(Long.valueOf(txtFaxNumber.getText()));
        Person.setEmail_Address(txtEmailAddress.getText());
        Person.setSocial_Security_Number(Integer.parseInt(txtSocialSecurityNumber.getText()));
        Person.setMedical_record_Number(txtMedicalRecordNumber.getText());
        Person.setHealth_plan_beneficiary_number(Long.valueOf(txtHealthPlanNumber.getText()));
        Person.setBank_account_numbers(Long.valueOf(txtBankAccountNumber.getText()));
        Person.setLicense_number(txtLicenseNumber.getText());
        Person.setVehicle_identifiers_and_serial_numbers_including_license_plates(txtVehicleIdentifier.getText());
        Person.setDevice_identifiers_and_serial_numbers(txtDeviceIdentifier.getText());
        Person.setLinkedIn(txtLinkedin.getText());
        Person.setInternet_protocol_addresses(txtIPAddress.getText());
        Person.setBiometric_identifiers(txtBiometricIdentifiers.getText());
        Person.setFull_face_photos_and_comparable_images(txtPhoto.getText());
        Person.setUnique_identifying_number(Long.valueOf(txtUniqueIdentifier.getText()));
        Person.setImg(im);
        
        if(validateIt()){
            JOptionPane.showMessageDialog(this, "Profile created");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        
        JFileChooser imgPhotoBrowse = new JFileChooser();
        FileNameExtensionFilter objFileExt = new FileNameExtensionFilter("gif", "png", "jpg", "jpeg", "IMAGES");
        imgPhotoBrowse.addChoosableFileFilter(objFileExt);
        int objOpenDlg = imgPhotoBrowse.showOpenDialog(null);
        if( objOpenDlg == JFileChooser.APPROVE_OPTION){
          File imgSelectedFile =   imgPhotoBrowse.getSelectedFile();
          String imgSelectedPath = imgSelectedFile.getAbsolutePath();
          JOptionPane.showMessageDialog(null, imgSelectedPath);
          txtPhoto.setText(imgSelectedPath);
          ii = new ImageIcon(imgSelectedPath);
          im = ii.getImage().getScaledInstance(lblImage.getWidth(),lblImage.getHeight(), Image.SCALE_SMOOTH);
          Person.setImg(im);
        }
    }//GEN-LAST:event_btnImageActionPerformed
boolean validateIt(){
        boolean b = false;
        if(txtName.getText().isEmpty() || !Pattern.matches("^[a-zA-Z ]+$", txtName.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Valid Name");
            txtName.requestFocus();
        }
        
        if(txtGeographicaldata.getText().equals("") || !Pattern.matches("^[0-9a-zA-Z ]+$", txtGeographicaldata.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Geographical Data");
            txtGeographicaldata.requestFocus();
        }
        if(txtTelephoneNumber.getText().equals("") || !Pattern.matches("^[0-9]{10}$",txtTelephoneNumber.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Valid Phone Number");
            txtTelephoneNumber.requestFocus();
        }
        if(txtBankAccountNumber.getText().equals("") || !Pattern.matches("^[0-9]+$",txtBankAccountNumber.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Bank Details");
            txtBankAccountNumber.requestFocus();
        }
        
        if(txtSocialSecurityNumber.getText().equals("") || !Pattern.matches("^[0-9]{9}$",txtSocialSecurityNumber.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter Correct Social Security Number");
            txtSocialSecurityNumber.requestFocus();
        }
              
        if(txtEmailAddress.getText().equals("") || !Pattern.matches("^[a-zA-Z0-9.]+@[a-zA-Z.]+\\.[a-zA-Z]{2,}$",txtEmailAddress.getText())){
            b = false;
            JOptionPane.showMessageDialog(null, "Enter valid Email ID");
            txtEmailAddress.requestFocus();
        }
        else
            b= true;
        return b;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel labelBankaccountNumber;
    private javax.swing.JLabel labelBenificarNumbers;
    private javax.swing.JLabel labelBiometric;
    private javax.swing.JLabel labelCertificate;
    private javax.swing.JLabel labelDateOfBirth;
    private javax.swing.JLabel labelDeviceIdentifier;
    private javax.swing.JLabel labelEmailAddress;
    private javax.swing.JLabel labelFAXNumber;
    private javax.swing.JLabel labelGeographicalData;
    private javax.swing.JLabel labelIPAddress;
    private javax.swing.JLabel labelLinkedin;
    private javax.swing.JLabel labelMedicalRecordNumbers;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JLabel labelProfile;
    private javax.swing.JLabel labelSocialSecurityNumbers;
    private javax.swing.JLabel labelTelephoneNumber;
    private javax.swing.JLabel labelUniqueId;
    private javax.swing.JLabel labelVehicleIdentifier;
    private javax.swing.JLabel labellName;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtBankAccountNumber;
    private javax.swing.JTextField txtBiometricIdentifiers;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtDeviceIdentifier;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFaxNumber;
    private javax.swing.JTextField txtGeographicaldata;
    private javax.swing.JTextField txtHealthPlanNumber;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoto;
    private javax.swing.JTextField txtSocialSecurityNumber;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtUniqueIdentifier;
    private javax.swing.JTextField txtVehicleIdentifier;
    // End of variables declaration//GEN-END:variables
}
